export interface AtlasEntry {
  id: string;
  category: string;
  color: string;
}

const ATLAS: AtlasEntry[] = [
  // Combat
  { id: 'DIAMOND_SWORD', category: 'combat', color: '#4AEDD7' },
  { id: 'IRON_SWORD', category: 'combat', color: '#D8D8D8' },
  { id: 'GOLDEN_SWORD', category: 'combat', color: '#F4D142' },
  { id: 'STONE_SWORD', category: 'combat', color: '#7D7D7D' },
  { id: 'WOODEN_SWORD', category: 'combat', color: '#B3814F' },
  { id: 'NETHERITE_SWORD', category: 'combat', color: '#383838' },
  { id: 'BOW', category: 'combat', color: '#C2926A' },
  { id: 'ARROW', category: 'combat', color: '#E3E3E3' },
  { id: 'SHIELD', category: 'combat', color: '#8B4513' },
  { id: 'TOTEM_OF_UNDYING', category: 'combat', color: '#2E8B57' },

  // Tools
  { id: 'DIAMOND_PICKAXE', category: 'tools', color: '#4AEDD7' },
  { id: 'IRON_PICKAXE', category: 'tools', color: '#D8D8D8' },
  { id: 'GOLDEN_PICKAXE', category: 'tools', color: '#F4D142' },
  { id: 'STONE_PICKAXE', category: 'tools', color: '#7D7D7D' },
  { id: 'WOODEN_PICKAXE', category: 'tools', color: '#B3814F' },
  { id: 'NETHERITE_PICKAXE', category: 'tools', color: '#383838' },
  { id: 'SHEARS', category: 'tools', color: '#D8D8D8' },
  { id: 'FISHING_ROD', category: 'tools', color: '#8B4513' },
  { id: 'FLINT_AND_STEEL', category: 'tools', color: '#555555' },
  { id: 'BRUSH', category: 'tools', color: '#D2691E' },

  // Blocks
  { id: 'STONE', category: 'blocks', color: '#7D7D7D' },
  { id: 'GRASS_BLOCK', category: 'blocks', color: '#5D8C47' },
  { id: 'DIRT', category: 'blocks', color: '#8B5A2B' },
  { id: 'COBBLESTONE', category: 'blocks', color: '#7D7D7D' },
  { id: 'OAK_PLANKS', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_PLANKS', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_PLANKS', category: 'blocks', color: '#D2B48C' },
  { id: 'SAND', category: 'blocks', color: '#DBD3A0' },
  { id: 'GRAVEL', category: 'blocks', color: '#8C8C8C' },
  { id: 'GLASS', category: 'blocks', color: '#D0E8F2' },
  { id: 'BRICKS', category: 'blocks', color: '#B22222' },
  { id: 'OBSIDIAN', category: 'blocks', color: '#140E1F' },
  { id: 'BEDROCK', category: 'blocks', color: '#333333' },
  { id: 'DIAMOND_ORE', category: 'blocks', color: '#4AEDD7' },
  { id: 'IRON_ORE', category: 'blocks', color: '#D8AF93' },
  { id: 'COAL_ORE', category: 'blocks', color: '#2F2F2F' },
  { id: 'GOLD_ORE', category: 'blocks', color: '#F4D142' },
  { id: 'EMERALD_ORE', category: 'blocks', color: '#50C878' },
  { id: 'REDSTONE_ORE', category: 'blocks', color: '#B22222' },
  { id: 'LAPIS_ORE', category: 'blocks', color: '#1E3A8A' },
  { id: 'COPPER_ORE', category: 'blocks', color: '#B87333' },
  { id: 'DIORITE', category: 'blocks', color: '#D3D3D3' },
  { id: 'ANDESITE', category: 'blocks', color: '#A9A9A9' },
  { id: 'GRANITE', category: 'blocks', color: '#D2691E' },
  { id: 'DEEPSLATE', category: 'blocks', color: '#2F2F2F' },
  { id: 'CALCITE', category: 'blocks', color: '#F5F5F5' },
  { id: 'TUFF', category: 'blocks', color: '#4A4A4A' },
  { id: 'AMETHYST_BLOCK', category: 'blocks', color: '#9966CC' },
  { id: 'DRIPSTONE_BLOCK', category: 'blocks', color: '#8B7355' },

  // Ores / Ingots
  { id: 'DIAMOND', category: 'materials', color: '#4AEDD7' },
  { id: 'IRON_INGOT', category: 'materials', color: '#D8D8D8' },
  { id: 'GOLD_INGOT', category: 'materials', color: '#F4D142' },
  { id: 'COPPER_INGOT', category: 'materials', color: '#B87333' },
  { id: 'NETHERITE_INGOT', category: 'materials', color: '#383838' },
  { id: 'EMERALD', category: 'materials', color: '#50C878' },
  { id: 'REDSTONE', category: 'materials', color: '#B22222' },
  { id: 'LAPIS_LAZULI', category: 'materials', color: '#1E3A8A' },
  { id: 'COAL', category: 'materials', color: '#2F2F2F' },
  { id: 'QUARTZ', category: 'materials', color: '#F5F5F5' },
  { id: 'AMETHYST_SHARD', category: 'materials', color: '#9966CC' },
  { id: 'RAW_IRON', category: 'materials', color: '#D8AF93' },
  { id: 'RAW_GOLD', category: 'materials', color: '#F4D142' },
  { id: 'RAW_COPPER', category: 'materials', color: '#B87333' },
  { id: 'COPPER_BLOCK', category: 'blocks', color: '#B87333' },
  { id: 'IRON_BLOCK', category: 'blocks', color: '#D8D8D8' },
  { id: 'GOLD_BLOCK', category: 'blocks', color: '#F4D142' },
  { id: 'DIAMOND_BLOCK', category: 'blocks', color: '#4AEDD7' },
  { id: 'EMERALD_BLOCK', category: 'blocks', color: '#50C878' },
  { id: 'REDSTONE_BLOCK', category: 'blocks', color: '#B22222' },
  { id: 'LAPIS_BLOCK', category: 'blocks', color: '#1E3A8A' },
  { id: 'COAL_BLOCK', category: 'blocks', color: '#2F2F2F' },
  { id: 'NETHERITE_BLOCK', category: 'blocks', color: '#383838' },
  { id: 'QUARTZ_BLOCK', category: 'blocks', color: '#F5F5F5' },

  // Food
  { id: 'APPLE', category: 'food', color: '#FF0000' },
  { id: 'GOLDEN_APPLE', category: 'food', color: '#F4D142' },
  { id: 'ENCHANTED_GOLDEN_APPLE', category: 'food', color: '#F4D142' },
  { id: 'MELON_SLICE', category: 'food', color: '#FF0000' },
  { id: 'WHEAT', category: 'food', color: '#D2B48C' },
  { id: 'BREAD', category: 'food', color: '#D2B48C' },
  { id: 'CARROT', category: 'food', color: '#FF8C00' },
  { id: 'GOLDEN_CARROT', category: 'food', color: '#F4D142' },
  { id: 'POTATO', category: 'food', color: '#D2B48C' },
  { id: 'BAKED_POTATO', category: 'food', color: '#D2B48C' },
  { id: 'BEETROOT', category: 'food', color: '#8B0000' },
  { id: 'PUMPKIN_PIE', category: 'food', color: '#FF8C00' },
  { id: 'COOKIE', category: 'food', color: '#8B4513' },
  { id: 'CAKE', category: 'food', color: '#FFB6C1' },
  { id: 'COOKED_BEEF', category: 'food', color: '#8B4513' },
  { id: 'COOKED_PORKCHOP', category: 'food', color: '#8B4513' },
  { id: 'COOKED_CHICKEN', category: 'food', color: '#D2691E' },
  { id: 'COOKED_MUTTON', category: 'food', color: '#8B4513' },
  { id: 'COOKED_RABBIT', category: 'food', color: '#8B4513' },
  { id: 'COOKED_COD', category: 'food', color: '#D2B48C' },
  { id: 'COOKED_SALMON', category: 'food', color: '#FF69B4' },
  { id: 'TROPICAL_FISH', category: 'food', color: '#FF8C00' },
  { id: 'PUFFERFISH', category: 'food', color: '#FFD700' },
  { id: 'DRIED_KELP', category: 'food', color: '#2E8B57' },
  { id: 'SWEET_BERRIES', category: 'food', color: '#FF0000' },
  { id: 'GLOW_BERRIES', category: 'food', color: '#FFD700' },
  { id: 'HONEY_BOTTLE', category: 'food', color: '#FFD700' },
  { id: 'CHORUS_FRUIT', category: 'food', color: '#800080' },
  { id: 'ROTTEN_FLESH', category: 'food', color: '#8B4513' },
  { id: 'SPIDER_EYE', category: 'food', color: '#8B0000' },

  // Redstone
  { id: 'REDSTONE_TORCH', category: 'redstone', color: '#B22222' },
  { id: 'LEVER', category: 'redstone', color: '#8B4513' },
  { id: 'STONE_BUTTON', category: 'redstone', color: '#7D7D7D' },
  { id: 'OAK_BUTTON', category: 'redstone', color: '#B3814F' },
  { id: 'PISTON', category: 'redstone', color: '#8B4513' },
  { id: 'STICKY_PISTON', category: 'redstone', color: '#8B4513' },
  { id: 'SLIME_BLOCK', category: 'redstone', color: '#32CD32' },
  { id: 'HONEY_BLOCK', category: 'redstone', color: '#FFD700' },
  { id: 'OBSERVER', category: 'redstone', color: '#7D7D7D' },
  { id: 'HOPPER', category: 'redstone', color: '#555555' },
  { id: 'DROPPER', category: 'redstone', color: '#7D7D7D' },
  { id: 'DISPENSER', category: 'redstone', color: '#7D7D7D' },
  { id: 'COMPARATOR', category: 'redstone', color: '#B22222' },
  { id: 'REPEATER', category: 'redstone', color: '#B22222' },
  { id: 'TARGET', category: 'redstone', color: '#FF0000' },
  { id: 'LECTERN', category: 'redstone', color: '#8B4513' },
  { id: 'LIGHTNING_ROD', category: 'redstone', color: '#B87333' },
  { id: 'SCULK_SENSOR', category: 'redstone', color: '#00CED1' },
  { id: 'CALIBRATED_SCULK_SENSOR', category: 'redstone', color: '#00CED1' },

  // Transport
  { id: 'MINECART', category: 'transport', color: '#555555' },
  { id: 'CHEST_MINECART', category: 'transport', color: '#8B4513' },
  { id: 'FURNACE_MINECART', category: 'transport', color: '#7D7D7D' },
  { id: 'HOPPER_MINECART', category: 'transport', color: '#555555' },
  { id: 'TNT_MINECART', category: 'transport', color: '#FF0000' },
  { id: 'RAIL', category: 'transport', color: '#7D7D7D' },
  { id: 'POWERED_RAIL', category: 'transport', color: '#B22222' },
  { id: 'DETECTOR_RAIL', category: 'transport', color: '#B22222' },
  { id: 'ACTIVATOR_RAIL', category: 'transport', color: '#B22222' },
  { id: 'BOAT', category: 'transport', color: '#B3814F' },
  { id: 'CHEST_BOAT', category: 'transport', color: '#B3814F' },
  { id: 'SADDLE', category: 'transport', color: '#8B4513' },
  { id: 'ELYTRA', category: 'transport', color: '#E0FFFF' },
  { id: 'OAK_CHEST_BOAT', category: 'transport', color: '#B3814F' },

  // Brewing
  { id: 'BLAZE_POWDER', category: 'brewing', color: '#FFD700' },
  { id: 'BLAZE_ROD', category: 'brewing', color: '#FFD700' },
  { id: 'GHAST_TEAR', category: 'brewing', color: '#E0FFFF' },
  { id: 'NETHER_WART', category: 'brewing', color: '#8B0000' },
  { id: 'GLOWSTONE_DUST', category: 'brewing', color: '#FFD700' },
  { id: 'MAGMA_CREAM', category: 'brewing', color: '#FF4500' },
  { id: 'SUGAR', category: 'brewing', color: '#F5F5F5' },
  { id: 'GLISTERING_MELON_SLICE', category: 'brewing', color: '#FFD700' },
  { id: 'RABBIT_FOOT', category: 'brewing', color: '#FF69B4' },
  { id: 'DRAGON_BREATH', category: 'brewing', color: '#800080' },
  { id: 'SPLASH_POTION', category: 'brewing', color: '#4169E1' },
  { id: 'LINGERING_POTION', category: 'brewing', color: '#7CFC00' },
  { id: 'GLASS_BOTTLE', category: 'brewing', color: '#D0E8F2' },
  { id: 'WATER_BUCKET', category: 'brewing', color: '#4169E1' },
  { id: 'LAVA_BUCKET', category: 'brewing', color: '#FF4500' },
  { id: 'MILK_BUCKET', category: 'brewing', color: '#F5F5F5' },
  { id: 'POTION', category: 'brewing', color: '#4169E1' },

  // Dyes
  { id: 'WHITE_DYE', category: 'dyes', color: '#FFFFFF' },
  { id: 'ORANGE_DYE', category: 'dyes', color: '#FF8C00' },
  { id: 'MAGENTA_DYE', category: 'dyes', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_DYE', category: 'dyes', color: '#ADD8E6' },
  { id: 'YELLOW_DYE', category: 'dyes', color: '#FFD700' },
  { id: 'LIME_DYE', category: 'dyes', color: '#32CD32' },
  { id: 'PINK_DYE', category: 'dyes', color: '#FFB6C1' },
  { id: 'GRAY_DYE', category: 'dyes', color: '#808080' },
  { id: 'LIGHT_GRAY_DYE', category: 'dyes', color: '#D3D3D3' },
  { id: 'CYAN_DYE', category: 'dyes', color: '#00FFFF' },
  { id: 'PURPLE_DYE', category: 'dyes', color: '#800080' },
  { id: 'BLUE_DYE', category: 'dyes', color: '#0000FF' },
  { id: 'BROWN_DYE', category: 'dyes', color: '#8B4513' },
  { id: 'GREEN_DYE', category: 'dyes', color: '#008000' },
  { id: 'RED_DYE', category: 'dyes', color: '#FF0000' },
  { id: 'BLACK_DYE', category: 'dyes', color: '#000000' },

  // Misc items
  { id: 'EXPERIENCE_BOTTLE', category: 'misc', color: '#7CFC00' },
  { id: 'FIREWORK_ROCKET', category: 'misc', color: '#FF4500' },
  { id: 'NAME_TAG', category: 'misc', color: '#F5F5F5' },
  { id: 'LEAD', category: 'misc', color: '#8B4513' },
  { id: 'ENDER_PEARL', category: 'misc', color: '#2E8B57' },
  { id: 'ENDER_EYE', category: 'misc', color: '#2E8B57' },
  { id: 'ENCHANTED_BOOK', category: 'misc', color: '#800080' },
  { id: 'WRITABLE_BOOK', category: 'misc', color: '#F5F5DC' },
  { id: 'WRITTEN_BOOK', category: 'misc', color: '#8B4513' },
  { id: 'MAP', category: 'misc', color: '#D2B48C' },
  { id: 'COMPASS', category: 'misc', color: '#C0C0C0' },
  { id: 'RECOVERY_COMPASS', category: 'misc', color: '#00CED1' },
  { id: 'CLOCK', category: 'misc', color: '#FFD700' },
  { id: 'SPYGLASS', category: 'misc', color: '#8B4513' },
  { id: 'ECHO_SHARD', category: 'misc', color: '#00CED1' },
  { id: 'DISC_FRAGMENT_5', category: 'misc', color: '#FF4500' },
  { id: 'NETHERITE_UPGRADE_SMITHING_TEMPLATE', category: 'misc', color: '#383838' },
  { id: 'SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#C0C0C0' },
  { id: 'DUNE_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#D2B48C' },
  { id: 'COAST_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#4169E1' },
  { id: 'WILD_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#2E8B57' },
  { id: 'WARD_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#00CED1' },
  { id: 'EYE_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#7CFC00' },
  { id: 'VEX_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#800080' },
  { id: 'TIDE_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#4169E1' },
  { id: 'SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#FF69B4' },
  { id: 'RIB_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#B22222' },
  { id: 'SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#800080' },
  { id: 'WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#FFD700' },
  { id: 'SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#D2B48C' },
  { id: 'SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#2F2F2F' },
  { id: 'RAISER_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#D2B48C' },
  { id: 'HOST_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#D2B48C' },
  { id: 'FLOW_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#FFD700' },
  { id: 'BOLT_ARMOR_TRIM_SMITHING_TEMPLATE', category: 'misc', color: '#C0C0C0' },
  { id: 'BREEZE_ROD', category: 'misc', color: '#ADD8E6' },
  { id: 'WIND_CHARGE', category: 'misc', color: '#ADD8E6' },
  { id: 'OMINOUS_TRIAL_KEY', category: 'misc', color: '#00CED1' },
  { id: 'TRIAL_KEY', category: 'misc', color: '#FFD700' },
  { id: 'HEAVY_CORE', category: 'misc', color: '#383838' },
  { id: 'MACE', category: 'misc', color: '#B87333' },
  { id: 'RESIN_CLUMP', category: 'misc', color: '#8B4513' },
  { id: 'RESIN_BRICK', category: 'misc', color: '#8B4513' },

  // Common blocks
  { id: 'CHEST', category: 'blocks', color: '#8B4513' },
  { id: 'TRAPPED_CHEST', category: 'blocks', color: '#8B4513' },
  { id: 'ENDER_CHEST', category: 'blocks', color: '#2E8B57' },
  { id: 'BARREL', category: 'blocks', color: '#8B4513' },
  { id: 'FURNACE', category: 'blocks', color: '#7D7D7D' },
  { id: 'BLAST_FURNACE', category: 'blocks', color: '#2F2F2F' },
  { id: 'SMOKER', category: 'blocks', color: '#2F2F2F' },
  { id: 'CAMPFIRE', category: 'blocks', color: '#8B4513' },
  { id: 'SOUL_CAMPFIRE', category: 'blocks', color: '#00CED1' },
  { id: 'CAULDRON', category: 'blocks', color: '#2F2F2F' },
  { id: 'BREWING_STAND', category: 'blocks', color: '#2F2F2F' },
  { id: 'ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'CHIPPED_ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'DAMAGED_ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'GRINDSTONE', category: 'blocks', color: '#7D7D7D' },
  { id: 'SMITHING_TABLE', category: 'blocks', color: '#8B4513' },
  { id: 'FLETCHING_TABLE', category: 'blocks', color: '#D2B48C' },
  { id: 'CARTOGRAPHY_TABLE', category: 'blocks', color: '#8B4513' },
  { id: 'LOOM', category: 'blocks', color: '#8B4513' },
  { id: 'COMPOSTER', category: 'blocks', color: '#8B4513' },
  { id: 'ENCHANTING_TABLE', category: 'blocks', color: '#800080' },
  { id: 'BEACON', category: 'blocks', color: '#00CED1' },
  { id: 'CONDUIT', category: 'blocks', color: '#FF69B4' },
  { id: 'END_PORTAL_FRAME', category: 'blocks', color: '#2E8B57' },
  { id: 'JUKEBOX', category: 'blocks', color: '#8B4513' },
  { id: 'NOTE_BLOCK', category: 'blocks', color: '#8B4513' },
  { id: 'TNT', category: 'blocks', color: '#FF0000' },
  { id: 'BOOKSHELF', category: 'blocks', color: '#8B4513' },
  { id: 'MOSSY_COBBLESTONE', category: 'blocks', color: '#6E8B5E' },

  // Wood / logs
  { id: 'OAK_LOG', category: 'blocks', color: '#8B4513' },
  { id: 'SPRUCE_LOG', category: 'blocks', color: '#3E2723' },
  { id: 'BIRCH_LOG', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_LOG', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_LOG', category: 'blocks', color: '#8B4513' },
  { id: 'DARK_OAK_LOG', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_LOG', category: 'blocks', color: '#3E2723' },
  { id: 'CHERRY_LOG', category: 'blocks', color: '#D2B48C' },
  { id: 'PALE_OAK_LOG', category: 'blocks', color: '#E3E3E3' },

  // Wool
  { id: 'WHITE_WOOL', category: 'blocks', color: '#FFFFFF' },
  { id: 'ORANGE_WOOL', category: 'blocks', color: '#FF8C00' },
  { id: 'MAGENTA_WOOL', category: 'blocks', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_WOOL', category: 'blocks', color: '#ADD8E6' },
  { id: 'YELLOW_WOOL', category: 'blocks', color: '#FFD700' },
  { id: 'LIME_WOOL', category: 'blocks', color: '#32CD32' },
  { id: 'PINK_WOOL', category: 'blocks', color: '#FFB6C1' },
  { id: 'GRAY_WOOL', category: 'blocks', color: '#808080' },
  { id: 'LIGHT_GRAY_WOOL', category: 'blocks', color: '#D3D3D3' },
  { id: 'CYAN_WOOL', category: 'blocks', color: '#00FFFF' },
  { id: 'PURPLE_WOOL', category: 'blocks', color: '#800080' },
  { id: 'BLUE_WOOL', category: 'blocks', color: '#0000FF' },
  { id: 'BROWN_WOOL', category: 'blocks', color: '#8B4513' },
  { id: 'GREEN_WOOL', category: 'blocks', color: '#008000' },
  { id: 'RED_WOOL', category: 'blocks', color: '#FF0000' },
  { id: 'BLACK_WOOL', category: 'blocks', color: '#000000' },

  // Concrete
  { id: 'WHITE_CONCRETE', category: 'blocks', color: '#FFFFFF' },
  { id: 'ORANGE_CONCRETE', category: 'blocks', color: '#FF8C00' },
  { id: 'MAGENTA_CONCRETE', category: 'blocks', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_CONCRETE', category: 'blocks', color: '#ADD8E6' },
  { id: 'YELLOW_CONCRETE', category: 'blocks', color: '#FFD700' },
  { id: 'LIME_CONCRETE', category: 'blocks', color: '#32CD32' },
  { id: 'PINK_CONCRETE', category: 'blocks', color: '#FFB6C1' },
  { id: 'GRAY_CONCRETE', category: 'blocks', color: '#808080' },
  { id: 'LIGHT_GRAY_CONCRETE', category: 'blocks', color: '#D3D3D3' },
  { id: 'CYAN_CONCRETE', category: 'blocks', color: '#00FFFF' },
  { id: 'PURPLE_CONCRETE', category: 'blocks', color: '#800080' },
  { id: 'BLUE_CONCRETE', category: 'blocks', color: '#0000FF' },
  { id: 'BROWN_CONCRETE', category: 'blocks', color: '#8B4513' },
  { id: 'GREEN_CONCRETE', category: 'blocks', color: '#008000' },
  { id: 'RED_CONCRETE', category: 'blocks', color: '#FF0000' },
  { id: 'BLACK_CONCRETE', category: 'blocks', color: '#000000' },

  // Terracotta
  { id: 'TERRACOTTA', category: 'blocks', color: '#A0522D' },
  { id: 'WHITE_TERRACOTTA', category: 'blocks', color: '#D3D3D3' },
  { id: 'ORANGE_TERRACOTTA', category: 'blocks', color: '#A0522D' },
  { id: 'MAGENTA_TERRACOTTA', category: 'blocks', color: '#915F6D' },
  { id: 'LIGHT_BLUE_TERRACOTTA', category: 'blocks', color: '#6B8E9F' },
  { id: 'YELLOW_TERRACOTTA', category: 'blocks', color: '#B8860B' },
  { id: 'LIME_TERRACOTTA', category: 'blocks', color: '#556B2F' },
  { id: 'PINK_TERRACOTTA', category: 'blocks', color: '#A0522D' },
  { id: 'GRAY_TERRACOTTA', category: 'blocks', color: '#4A4A4A' },
  { id: 'LIGHT_GRAY_TERRACOTTA', category: 'blocks', color: '#8B8378' },
  { id: 'CYAN_TERRACOTTA', category: 'blocks', color: '#4A766E' },
  { id: 'PURPLE_TERRACOTTA', category: 'blocks', color: '#4B0082' },
  { id: 'BLUE_TERRACOTTA', category: 'blocks', color: '#2F2F4F' },
  { id: 'BROWN_TERRACOTTA', category: 'blocks', color: '#3E2723' },
  { id: 'GREEN_TERRACOTTA', category: 'blocks', color: '#2E8B57' },
  { id: 'RED_TERRACOTTA', category: 'blocks', color: '#8B0000' },
  { id: 'BLACK_TERRACOTTA', category: 'blocks', color: '#1C1C1C' },

  // Player heads / skulls
  { id: 'PLAYER_HEAD', category: 'misc', color: '#F5C6A5' },
  { id: 'SKELETON_SKULL', category: 'misc', color: '#F5F5F5' },
  { id: 'WITHER_SKELETON_SKULL', category: 'misc', color: '#2F2F2F' },
  { id: 'ZOMBIE_HEAD', category: 'misc', color: '#2E8B57' },
  { id: 'CREEPER_HEAD', category: 'misc', color: '#32CD32' },
  { id: 'DRAGON_HEAD', category: 'misc', color: '#2E8B57' },
  { id: 'PIGLIN_HEAD', category: 'misc', color: '#F4A460' },

  // Armor
  { id: 'LEATHER_HELMET', category: 'combat', color: '#8B4513' },
  { id: 'LEATHER_CHESTPLATE', category: 'combat', color: '#8B4513' },
  { id: 'LEATHER_LEGGINGS', category: 'combat', color: '#8B4513' },
  { id: 'LEATHER_BOOTS', category: 'combat', color: '#8B4513' },
  { id: 'CHAINMAIL_HELMET', category: 'combat', color: '#808080' },
  { id: 'CHAINMAIL_CHESTPLATE', category: 'combat', color: '#808080' },
  { id: 'CHAINMAIL_LEGGINGS', category: 'combat', color: '#808080' },
  { id: 'CHAINMAIL_BOOTS', category: 'combat', color: '#808080' },
  { id: 'IRON_HELMET', category: 'combat', color: '#D8D8D8' },
  { id: 'IRON_CHESTPLATE', category: 'combat', color: '#D8D8D8' },
  { id: 'IRON_LEGGINGS', category: 'combat', color: '#D8D8D8' },
  { id: 'IRON_BOOTS', category: 'combat', color: '#D8D8D8' },
  { id: 'GOLDEN_HELMET', category: 'combat', color: '#F4D142' },
  { id: 'GOLDEN_CHESTPLATE', category: 'combat', color: '#F4D142' },
  { id: 'GOLDEN_LEGGINGS', category: 'combat', color: '#F4D142' },
  { id: 'GOLDEN_BOOTS', category: 'combat', color: '#F4D142' },
  { id: 'DIAMOND_HELMET', category: 'combat', color: '#4AEDD7' },
  { id: 'DIAMOND_CHESTPLATE', category: 'combat', color: '#4AEDD7' },
  { id: 'DIAMOND_LEGGINGS', category: 'combat', color: '#4AEDD7' },
  { id: 'DIAMOND_BOOTS', category: 'combat', color: '#4AEDD7' },
  { id: 'NETHERITE_HELMET', category: 'combat', color: '#383838' },
  { id: 'NETHERITE_CHESTPLATE', category: 'combat', color: '#383838' },
  { id: 'NETHERITE_LEGGINGS', category: 'combat', color: '#383838' },
  { id: 'NETHERITE_BOOTS', category: 'combat', color: '#383838' },
  { id: 'TURTLE_HELMET', category: 'combat', color: '#2E8B57' },
  { id: 'WOLF_ARMOR', category: 'combat', color: '#8B4513' },

  // Additional common items
  { id: 'BOOK', category: 'misc', color: '#8B4513' },
  { id: 'PAPER', category: 'misc', color: '#F5F5F5' },
  { id: 'FEATHER', category: 'misc', color: '#F5F5F5' },
  { id: 'FLINT', category: 'misc', color: '#333333' },
  { id: 'STICK', category: 'misc', color: '#8B4513' },
  { id: 'BOWL', category: 'misc', color: '#8B4513' },
  { id: 'STRING', category: 'misc', color: '#F5F5F5' },
  { id: 'GUNPOWDER', category: 'misc', color: '#333333' },
  { id: 'WHEAT_SEEDS', category: 'misc', color: '#8B4513' },
  { id: 'COCOA_BEANS', category: 'misc', color: '#8B4513' },
  { id: 'INK_SAC', category: 'misc', color: '#000000' },
  { id: 'GLOW_INK_SAC', category: 'misc', color: '#00CED1' },
  { id: 'BONE_MEAL', category: 'misc', color: '#F5F5F5' },
  { id: 'BONE', category: 'misc', color: '#F5F5F5' },
  { id: 'LEATHER', category: 'misc', color: '#8B4513' },
  { id: 'RABBIT_HIDE', category: 'misc', color: '#F5F5F5' },
  { id: 'CLAY_BALL', category: 'misc', color: '#A9A9A9' },
  { id: 'SNOWBALL', category: 'misc', color: '#F0F8FF' },
  { id: 'SLIMEBALL', category: 'misc', color: '#32CD32' },
  { id: 'EGG', category: 'misc', color: '#F5F5F5' },
  { id: 'ARMADILLO_SCUTE', category: 'misc', color: '#8B4513' },
  { id: 'NAUTILUS_SHELL', category: 'misc', color: '#FFB6C1' },
  { id: 'HEART_OF_THE_SEA', category: 'misc', color: '#00CED1' },
  { id: 'SCUTE', category: 'misc', color: '#2E8B57' },
  { id: 'PHANTOM_MEMBRANE', category: 'misc', color: '#D3D3D3' },
  { id: 'SHULKER_SHELL', category: 'misc', color: '#800080' },
  { id: 'POPPED_CHORUS_FRUIT', category: 'misc', color: '#D3D3D3' },
  { id: 'DRAGON_EGG', category: 'misc', color: '#2E8B57' },
  { id: 'NETHER_STAR', category: 'misc', color: '#F5F5F5' },
  { id: 'PRISMARINE_SHARD', category: 'misc', color: '#2E8B57' },
  { id: 'PRISMARINE_CRYSTALS', category: 'misc', color: '#2E8B57' },
  { id: 'CLAY', category: 'blocks', color: '#A9A9A9' },
  { id: 'FARMLAND', category: 'blocks', color: '#8B4513' },
  { id: 'GRASS_PATH', category: 'blocks', color: '#5D8C47' },
  { id: 'DIRT_PATH', category: 'blocks', color: '#8B5A2B' },
  { id: 'COARSE_DIRT', category: 'blocks', color: '#8B5A2B' },
  { id: 'ROOTED_DIRT', category: 'blocks', color: '#8B5A2B' },
  { id: 'PODZOL', category: 'blocks', color: '#5D4037' },
  { id: 'MYCELIUM', category: 'blocks', color: '#8B7B8B' },
  { id: 'SNOW', category: 'blocks', color: '#F0F8FF' },
  { id: 'ICE', category: 'blocks', color: '#ADD8E6' },
  { id: 'PACKED_ICE', category: 'blocks', color: '#ADD8E6' },
  { id: 'BLUE_ICE', category: 'blocks', color: '#4169E1' },
  { id: 'FROSTED_ICE', category: 'blocks', color: '#ADD8E6' },
  { id: 'MAGMA_BLOCK', category: 'blocks', color: '#FF4500' },
  { id: 'SOUL_SAND', category: 'blocks', color: '#4A2C2A' },
  { id: 'SOUL_SOIL', category: 'blocks', color: '#3E2723' },
  { id: 'BASALT', category: 'blocks', color: '#2F2F2F' },
  { id: 'POLISHED_BASALT', category: 'blocks', color: '#2F2F2F' },
  { id: 'SMOOTH_BASALT', category: 'blocks', color: '#2F2F2F' },
  { id: 'BLACKSTONE', category: 'blocks', color: '#2F2F2F' },
  { id: 'POLISHED_BLACKSTONE', category: 'blocks', color: '#2F2F2F' },
  { id: 'CHISELED_POLISHED_BLACKSTONE', category: 'blocks', color: '#2F2F2F' },
  { id: 'POLISHED_BLACKSTONE_BRICKS', category: 'blocks', color: '#2F2F2F' },
  { id: 'CRACKED_POLISHED_BLACKSTONE_BRICKS', category: 'blocks', color: '#2F2F2F' },
  { id: 'GILDED_BLACKSTONE', category: 'blocks', color: '#FFD700' },
  { id: 'NETHERRACK', category: 'blocks', color: '#8B0000' },
  { id: 'NETHER_GOLD_ORE', category: 'blocks', color: '#F4D142' },
  { id: 'NETHER_QUARTZ_ORE', category: 'blocks', color: '#F5F5F5' },
  { id: 'ANCIENT_DEBRIS', category: 'blocks', color: '#5D4037' },
  { id: 'WARPED_NYLIUM', category: 'blocks', color: '#1E90FF' },
  { id: 'CRIMSON_NYLIUM', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_WART_BLOCK', category: 'blocks', color: '#1E90FF' },
  { id: 'NETHER_WART_BLOCK', category: 'blocks', color: '#8B0000' },
  { id: 'CRIMSON_STEM', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_STEM', category: 'blocks', color: '#1E90FF' },
  { id: 'STRIPPED_CRIMSON_STEM', category: 'blocks', color: '#8B0000' },
  { id: 'STRIPPED_WARPED_STEM', category: 'blocks', color: '#1E90FF' },
  { id: 'CRIMSON_PLANKS', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_PLANKS', category: 'blocks', color: '#1E90FF' },
  { id: 'SHROOMLIGHT', category: 'blocks', color: '#FF8C00' },
  { id: 'CRYING_OBSIDIAN', category: 'blocks', color: '#800080' },
  { id: 'LODESTONE', category: 'blocks', color: '#D3D3D3' },
  { id: 'RESPAWN_ANCHOR', category: 'blocks', color: '#800080' },
  { id: 'TARGET', category: 'blocks', color: '#FF0000' },
  { id: 'HONEYCOMB_BLOCK', category: 'blocks', color: '#FFD700' },
  { id: 'BEE_NEST', category: 'blocks', color: '#FFD700' },
  { id: 'BEEHIVE', category: 'blocks', color: '#FFD700' },
  { id: 'HONEY_BLOCK', category: 'blocks', color: '#FFD700' },
  { id: 'SLIME_BLOCK', category: 'blocks', color: '#32CD32' },
  { id: 'FROGLIGHT', category: 'blocks', color: '#F5F5DC' },
  { id: 'PEARLESCENT_FROGLIGHT', category: 'blocks', color: '#FFB6C1' },
  { id: 'VERDANT_FROGLIGHT', category: 'blocks', color: '#2E8B57' },
  { id: 'OCHRE_FROGLIGHT', category: 'blocks', color: '#F5F5DC' },
  { id: 'MUD', category: 'blocks', color: '#3E2723' },
  { id: 'PACKED_MUD', category: 'blocks', color: '#8B4513' },
  { id: 'MUD_BRICKS', category: 'blocks', color: '#8B4513' },
  { id: 'PITCHER_PLANT', category: 'blocks', color: '#800080' },
  { id: 'PITCHER_POD', category: 'blocks', color: '#800080' },
  { id: 'TORCHFLOWER', category: 'blocks', color: '#FFD700' },
  { id: 'TORCHFLOWER_SEEDS', category: 'blocks', color: '#FFD700' },
  { id: 'SPORE_BLOSSOM', category: 'blocks', color: '#FF69B4' },
  { id: 'AZALEA', category: 'blocks', color: '#2E8B57' },
  { id: 'FLOWERING_AZALEA', category: 'blocks', color: '#FF69B4' },
  { id: 'MOSS_BLOCK', category: 'blocks', color: '#2E8B57' },
  { id: 'MOSS_CARPET', category: 'blocks', color: '#2E8B57' },
  { id: 'HANGING_ROOTS', category: 'blocks', color: '#8B4513' },
  { id: 'BIG_DRIPLEAF', category: 'blocks', color: '#2E8B57' },
  { id: 'SMALL_DRIPLEAF', category: 'blocks', color: '#2E8B57' },
  { id: 'PINK_PETALS', category: 'blocks', color: '#FFB6C1' },
  { id: 'SPORE_BLOSSOM', category: 'blocks', color: '#FF69B4' },
  { id: 'SCULK', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_VEIN', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_CATALYST', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_SHRIEKER', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_SENSOR', category: 'blocks', color: '#00CED1' },
  { id: 'CALIBRATED_SCULK_SENSOR', category: 'blocks', color: '#00CED1' },
  { id: 'REINFORCED_DEEPSLATE', category: 'blocks', color: '#3A3A3A' },
  { id: 'END_PORTAL_FRAME', category: 'blocks', color: '#2E8B57' },
  { id: 'DRAGON_EGG', category: 'blocks', color: '#2E8B57' },
  { id: 'COMMAND_BLOCK', category: 'blocks', color: '#FFB6C1' },
  { id: 'REPEATING_COMMAND_BLOCK', category: 'blocks', color: '#4169E1' },
  { id: 'CHAIN_COMMAND_BLOCK', category: 'blocks', color: '#7CFC00' },
  { id: 'STRUCTURE_BLOCK', category: 'blocks', color: '#7CFC00' },
  { id: 'STRUCTURE_VOID', category: 'blocks', color: '#F5F5F5' },
  { id: 'JIGSAW', category: 'blocks', color: '#800080' },
  { id: 'BARRIER', category: 'blocks', color: '#FF0000' },
  { id: 'LIGHT', category: 'blocks', color: '#FFD700' },
  { id: 'TRIAL_SPAWNER', category: 'blocks', color: '#FFD700' },
  { id: 'OMINOUS_TRIAL_SPAWNER', category: 'blocks', color: '#00CED1' },
  { id: 'VAULT', category: 'blocks', color: '#B87333' },
  { id: 'OMINOUS_VAULT', category: 'blocks', color: '#00CED1' },
  { id: 'CREAKING_HEART', category: 'blocks', color: '#8B4513' },
  { id: 'PALE_OAK_PLANKS', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_LOG', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_WOOD', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_LEAVES', category: 'blocks', color: '#D3D3D3' },
  { id: 'PALE_MOSS_BLOCK', category: 'blocks', color: '#C0C0C0' },
  { id: 'PALE_MOSS_CARPET', category: 'blocks', color: '#C0C0C0' },
  { id: 'PALE_HANGING_MOSS', category: 'blocks', color: '#C0C0C0' },
  { id: 'OPEN_EYEBLOSSOM', category: 'blocks', color: '#C0C0C0' },
  { id: 'CLOSED_EYEBLOSSOM', category: 'blocks', color: '#808080' },
  { id: 'CREAKING_SPAWN_EGG', category: 'misc', color: '#C0C0C0' },
  { id: 'PALE_OAK_SAPLING', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_SIGN', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_HANGING_SIGN', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_DOOR', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_TRAPDOOR', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_PRESSURE_PLATE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_BUTTON', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_FENCE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_FENCE_GATE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_STAIRS', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_SLAB', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_BOAT', category: 'transport', color: '#E3E3E3' },
  { id: 'PALE_OAK_CHEST_BOAT', category: 'transport', color: '#E3E3E3' },
  { id: 'ACACIA_BOAT', category: 'transport', color: '#D2691E' },
  { id: 'ACACIA_CHEST_BOAT', category: 'transport', color: '#D2691E' },
  { id: 'BAMBOO_RAFT', category: 'transport', color: '#D2B48C' },
  { id: 'BAMBOO_CHEST_RAFT', category: 'transport', color: '#D2B48C' },
  { id: 'BIRCH_BOAT', category: 'transport', color: '#D2B48C' },
  { id: 'BIRCH_CHEST_BOAT', category: 'transport', color: '#D2B48C' },
  { id: 'CHERRY_BOAT', category: 'transport', color: '#FFB7C5' },
  { id: 'CHERRY_CHEST_BOAT', category: 'transport', color: '#FFB7C5' },
  { id: 'DARK_OAK_BOAT', category: 'transport', color: '#3E2723' },
  { id: 'DARK_OAK_CHEST_BOAT', category: 'transport', color: '#3E2723' },
  { id: 'JUNGLE_BOAT', category: 'transport', color: '#8B6914' },
  { id: 'JUNGLE_CHEST_BOAT', category: 'transport', color: '#8B6914' },
  { id: 'MANGROVE_BOAT', category: 'transport', color: '#8B4513' },
  { id: 'MANGROVE_CHEST_BOAT', category: 'transport', color: '#8B4513' },
  { id: 'OAK_CHEST_BOAT', category: 'transport', color: '#B3814F' },
  { id: 'SPRUCE_BOAT', category: 'transport', color: '#6F4E37' },
  { id: 'SPRUCE_CHEST_BOAT', category: 'transport', color: '#6F4E37' },
  { id: 'TNT', category: 'blocks', color: '#FF0000' },
  { id: 'BOOKSHELF', category: 'blocks', color: '#8B4513' },
  { id: 'MOSSY_COBBLESTONE', category: 'blocks', color: '#6E8B5E' },
  { id: 'OAK_STAIRS', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_STAIRS', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_STAIRS', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_STAIRS', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_STAIRS', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_STAIRS', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_STAIRS', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_STAIRS', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_STAIRS', category: 'blocks', color: '#D2B48C' },
  { id: 'BAMBOO_MOSAIC_STAIRS', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_STAIRS', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_STAIRS', category: 'blocks', color: '#1E90FF' },
  { id: 'OAK_SLAB', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_SLAB', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_SLAB', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_SLAB', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_SLAB', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_SLAB', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_SLAB', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_SLAB', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_SLAB', category: 'blocks', color: '#D2B48C' },
  { id: 'BAMBOO_MOSAIC_SLAB', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_SLAB', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_SLAB', category: 'blocks', color: '#1E90FF' },
  { id: 'OAK_FENCE', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_FENCE', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_FENCE', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_FENCE', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_FENCE', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_FENCE', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_FENCE', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_FENCE', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_FENCE', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_FENCE', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_FENCE', category: 'blocks', color: '#1E90FF' },
  { id: 'OAK_FENCE_GATE', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_FENCE_GATE', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_FENCE_GATE', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_FENCE_GATE', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_FENCE_GATE', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_FENCE_GATE', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_FENCE_GATE', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_FENCE_GATE', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_FENCE_GATE', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_FENCE_GATE', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_FENCE_GATE', category: 'blocks', color: '#1E90FF' },
  { id: 'OAK_DOOR', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_DOOR', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_DOOR', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_DOOR', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_DOOR', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_DOOR', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_DOOR', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_DOOR', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_DOOR', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_DOOR', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_DOOR', category: 'blocks', color: '#1E90FF' },
  { id: 'IRON_DOOR', category: 'blocks', color: '#D8D8D8' },
  { id: 'COPPER_DOOR', category: 'blocks', color: '#B87333' },
  { id: 'EXPOSED_COPPER_DOOR', category: 'blocks', color: '#8B7355' },
  { id: 'WEATHERED_COPPER_DOOR', category: 'blocks', color: '#6B8E6B' },
  { id: 'OXIDIZED_COPPER_DOOR', category: 'blocks', color: '#4A766E' },
  { id: 'WAXED_COPPER_DOOR', category: 'blocks', color: '#B87333' },
  { id: 'WAXED_EXPOSED_COPPER_DOOR', category: 'blocks', color: '#8B7355' },
  { id: 'WAXED_WEATHERED_COPPER_DOOR', category: 'blocks', color: '#6B8E6B' },
  { id: 'WAXED_OXIDIZED_COPPER_DOOR', category: 'blocks', color: '#4A766E' },
  { id: 'OAK_TRAPDOOR', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_TRAPDOOR', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_TRAPDOOR', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_TRAPDOOR', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_TRAPDOOR', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_TRAPDOOR', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_TRAPDOOR', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_TRAPDOOR', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_TRAPDOOR', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_TRAPDOOR', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_TRAPDOOR', category: 'blocks', color: '#1E90FF' },
  { id: 'IRON_TRAPDOOR', category: 'blocks', color: '#D8D8D8' },
  { id: 'COPPER_TRAPDOOR', category: 'blocks', color: '#B87333' },
  { id: 'EXPOSED_COPPER_TRAPDOOR', category: 'blocks', color: '#8B7355' },
  { id: 'WEATHERED_COPPER_TRAPDOOR', category: 'blocks', color: '#6B8E6B' },
  { id: 'OXIDIZED_COPPER_TRAPDOOR', category: 'blocks', color: '#4A766E' },
  { id: 'WAXED_COPPER_TRAPDOOR', category: 'blocks', color: '#B87333' },
  { id: 'WAXED_EXPOSED_COPPER_TRAPDOOR', category: 'blocks', color: '#8B7355' },
  { id: 'WAXED_WEATHERED_COPPER_TRAPDOOR', category: 'blocks', color: '#6B8E6B' },
  { id: 'WAXED_OXIDIZED_COPPER_TRAPDOOR', category: 'blocks', color: '#4A766E' },
  { id: 'OAK_PRESSURE_PLATE', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_PRESSURE_PLATE', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_PRESSURE_PLATE', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_PRESSURE_PLATE', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_PRESSURE_PLATE', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_PRESSURE_PLATE', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_PRESSURE_PLATE', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_PRESSURE_PLATE', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_PRESSURE_PLATE', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_PRESSURE_PLATE', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_PRESSURE_PLATE', category: 'blocks', color: '#1E90FF' },
  { id: 'POLISHED_BLACKSTONE_PRESSURE_PLATE', category: 'blocks', color: '#2F2F2F' },
  { id: 'HEAVY_WEIGHTED_PRESSURE_PLATE', category: 'blocks', color: '#D8D8D8' },
  { id: 'LIGHT_WEIGHTED_PRESSURE_PLATE', category: 'blocks', color: '#F4D142' },
  { id: 'OAK_SIGN', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_SIGN', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_SIGN', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_SIGN', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_SIGN', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_SIGN', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_SIGN', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_SIGN', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_SIGN', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_SIGN', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_SIGN', category: 'blocks', color: '#1E90FF' },
  { id: 'OAK_HANGING_SIGN', category: 'blocks', color: '#B3814F' },
  { id: 'SPRUCE_HANGING_SIGN', category: 'blocks', color: '#6F4E37' },
  { id: 'BIRCH_HANGING_SIGN', category: 'blocks', color: '#D2B48C' },
  { id: 'JUNGLE_HANGING_SIGN', category: 'blocks', color: '#8B6914' },
  { id: 'ACACIA_HANGING_SIGN', category: 'blocks', color: '#D2691E' },
  { id: 'DARK_OAK_HANGING_SIGN', category: 'blocks', color: '#3E2723' },
  { id: 'MANGROVE_HANGING_SIGN', category: 'blocks', color: '#8B4513' },
  { id: 'CHERRY_HANGING_SIGN', category: 'blocks', color: '#FFB7C5' },
  { id: 'BAMBOO_HANGING_SIGN', category: 'blocks', color: '#D2B48C' },
  { id: 'CRIMSON_HANGING_SIGN', category: 'blocks', color: '#8B0000' },
  { id: 'WARPED_HANGING_SIGN', category: 'blocks', color: '#1E90FF' },
  { id: 'SMITHING_TABLE', category: 'blocks', color: '#8B4513' },
  { id: 'FLETCHING_TABLE', category: 'blocks', color: '#D2B48C' },
  { id: 'CARTOGRAPHY_TABLE', category: 'blocks', color: '#8B4513' },
  { id: 'LOOM', category: 'blocks', color: '#8B4513' },
  { id: 'COMPOSTER', category: 'blocks', color: '#8B4513' },
  { id: 'GRINDSTONE', category: 'blocks', color: '#7D7D7D' },
  { id: 'STONECUTTER', category: 'blocks', color: '#7D7D7D' },
  { id: 'BELL', category: 'blocks', color: '#FFD700' },
  { id: 'LANTERN', category: 'blocks', color: '#FFD700' },
  { id: 'SOUL_LANTERN', category: 'blocks', color: '#00CED1' },
  { id: 'TORCH', category: 'blocks', color: '#FFD700' },
  { id: 'SOUL_TORCH', category: 'blocks', color: '#00CED1' },
  { id: 'REDSTONE_TORCH', category: 'blocks', color: '#B22222' },
  { id: 'END_ROD', category: 'blocks', color: '#F5F5F5' },
  { id: 'SEA_LANTERN', category: 'blocks', color: '#F5F5F5' },
  { id: 'GLOWSTONE', category: 'blocks', color: '#FFD700' },
  { id: 'REDSTONE_LAMP', category: 'blocks', color: '#B22222' },
  { id: 'BEACON', category: 'blocks', color: '#00CED1' },
  { id: 'CONDUIT', category: 'blocks', color: '#FF69B4' },
  { id: 'ENCHANTING_TABLE', category: 'blocks', color: '#800080' },
  { id: 'ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'CHIPPED_ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'DAMAGED_ANVIL', category: 'blocks', color: '#2F2F2F' },
  { id: 'JUKEBOX', category: 'blocks', color: '#8B4513' },
  { id: 'NOTE_BLOCK', category: 'blocks', color: '#8B4513' },
  { id: 'CRAFTING_TABLE', category: 'blocks', color: '#8B4513' },
  { id: 'FURNACE', category: 'blocks', color: '#7D7D7D' },
  { id: 'BLAST_FURNACE', category: 'blocks', color: '#2F2F2F' },
  { id: 'SMOKER', category: 'blocks', color: '#2F2F2F' },
  { id: 'CAMPFIRE', category: 'blocks', color: '#8B4513' },
  { id: 'SOUL_CAMPFIRE', category: 'blocks', color: '#00CED1' },
  { id: 'CAULDRON', category: 'blocks', color: '#2F2F2F' },
  { id: 'BREWING_STAND', category: 'blocks', color: '#2F2F2F' },
  { id: 'CHEST', category: 'blocks', color: '#8B4513' },
  { id: 'TRAPPED_CHEST', category: 'blocks', color: '#8B4513' },
  { id: 'ENDER_CHEST', category: 'blocks', color: '#2E8B57' },
  { id: 'BARREL', category: 'blocks', color: '#8B4513' },
  { id: 'DISPENSER', category: 'blocks', color: '#7D7D7D' },
  { id: 'DROPPER', category: 'blocks', color: '#7D7D7D' },
  { id: 'HOPPER', category: 'blocks', color: '#555555' },
  { id: 'SHULKER_BOX', category: 'blocks', color: '#800080' },
  { id: 'WHITE_SHULKER_BOX', category: 'blocks', color: '#FFFFFF' },
  { id: 'ORANGE_SHULKER_BOX', category: 'blocks', color: '#FF8C00' },
  { id: 'MAGENTA_SHULKER_BOX', category: 'blocks', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_SHULKER_BOX', category: 'blocks', color: '#ADD8E6' },
  { id: 'YELLOW_SHULKER_BOX', category: 'blocks', color: '#FFD700' },
  { id: 'LIME_SHULKER_BOX', category: 'blocks', color: '#32CD32' },
  { id: 'PINK_SHULKER_BOX', category: 'blocks', color: '#FFB6C1' },
  { id: 'GRAY_SHULKER_BOX', category: 'blocks', color: '#808080' },
  { id: 'LIGHT_GRAY_SHULKER_BOX', category: 'blocks', color: '#D3D3D3' },
  { id: 'CYAN_SHULKER_BOX', category: 'blocks', color: '#00FFFF' },
  { id: 'PURPLE_SHULKER_BOX', category: 'blocks', color: '#800080' },
  { id: 'BLUE_SHULKER_BOX', category: 'blocks', color: '#0000FF' },
  { id: 'BROWN_SHULKER_BOX', category: 'blocks', color: '#8B4513' },
  { id: 'GREEN_SHULKER_BOX', category: 'blocks', color: '#008000' },
  { id: 'RED_SHULKER_BOX', category: 'blocks', color: '#FF0000' },
  { id: 'BLACK_SHULKER_BOX', category: 'blocks', color: '#000000' },
  { id: 'WHITE_BED', category: 'blocks', color: '#FFFFFF' },
  { id: 'ORANGE_BED', category: 'blocks', color: '#FF8C00' },
  { id: 'MAGENTA_BED', category: 'blocks', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_BED', category: 'blocks', color: '#ADD8E6' },
  { id: 'YELLOW_BED', category: 'blocks', color: '#FFD700' },
  { id: 'LIME_BED', category: 'blocks', color: '#32CD32' },
  { id: 'PINK_BED', category: 'blocks', color: '#FFB6C1' },
  { id: 'GRAY_BED', category: 'blocks', color: '#808080' },
  { id: 'LIGHT_GRAY_BED', category: 'blocks', color: '#D3D3D3' },
  { id: 'CYAN_BED', category: 'blocks', color: '#00FFFF' },
  { id: 'PURPLE_BED', category: 'blocks', color: '#800080' },
  { id: 'BLUE_BED', category: 'blocks', color: '#0000FF' },
  { id: 'BROWN_BED', category: 'blocks', color: '#8B4513' },
  { id: 'GREEN_BED', category: 'blocks', color: '#008000' },
  { id: 'RED_BED', category: 'blocks', color: '#FF0000' },
  { id: 'BLACK_BED', category: 'blocks', color: '#000000' },
  { id: 'WHITE_CARPET', category: 'blocks', color: '#FFFFFF' },
  { id: 'ORANGE_CARPET', category: 'blocks', color: '#FF8C00' },
  { id: 'MAGENTA_CARPET', category: 'blocks', color: '#FF00FF' },
  { id: 'LIGHT_BLUE_CARPET', category: 'blocks', color: '#ADD8E6' },
  { id: 'YELLOW_CARPET', category: 'blocks', color: '#FFD700' },
  { id: 'LIME_CARPET', category: 'blocks', color: '#32CD32' },
  { id: 'PINK_CARPET', category: 'blocks', color: '#FFB6C1' },
  { id: 'GRAY_CARPET', category: 'blocks', color: '#808080' },
  { id: 'LIGHT_GRAY_CARPET', category: 'blocks', color: '#D3D3D3' },
  { id: 'CYAN_CARPET', category: 'blocks', color: '#00FFFF' },
  { id: 'PURPLE_CARPET', category: 'blocks', color: '#800080' },
  { id: 'BLUE_CARPET', category: 'blocks', color: '#0000FF' },
  { id: 'BROWN_CARPET', category: 'blocks', color: '#8B4513' },
  { id: 'GREEN_CARPET', category: 'blocks', color: '#008000' },
  { id: 'RED_CARPET', category: 'blocks', color: '#FF0000' },
  { id: 'BLACK_CARPET', category: 'blocks', color: '#000000' },
  { id: 'PAINTING', category: 'blocks', color: '#8B4513' },
  { id: 'ITEM_FRAME', category: 'blocks', color: '#8B4513' },
  { id: 'GLOW_ITEM_FRAME', category: 'blocks', color: '#FFD700' },
  { id: 'ARMOR_STAND', category: 'blocks', color: '#8B4513' },
  { id: 'OAK_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'SPRUCE_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'BIRCH_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'JUNGLE_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'ACACIA_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'DARK_OAK_SAPLING', category: 'blocks', color: '#2E8B57' },
  { id: 'CHERRY_SAPLING', category: 'blocks', color: '#FFB7C5' },
  { id: 'AZALEA', category: 'blocks', color: '#2E8B57' },
  { id: 'FLOWERING_AZALEA', category: 'blocks', color: '#FF69B4' },
  { id: 'DEAD_BUSH', category: 'blocks', color: '#8B4513' },
  { id: 'FERN', category: 'blocks', color: '#2E8B57' },
  { id: 'LARGE_FERN', category: 'blocks', color: '#2E8B57' },
  { id: 'TALL_GRASS', category: 'blocks', color: '#2E8B57' },
  { id: 'GRASS', category: 'blocks', color: '#2E8B57' },
  { id: 'SEAGRASS', category: 'blocks', color: '#2E8B57' },
  { id: 'TALL_SEAGRASS', category: 'blocks', color: '#2E8B57' },
  { id: 'SEA_PICKLE', category: 'blocks', color: '#2E8B57' },
  { id: 'KELP', category: 'blocks', color: '#2E8B57' },
  { id: 'DRIED_KELP_BLOCK', category: 'blocks', color: '#2E8B57' },
  { id: 'BAMBOO', category: 'blocks', color: '#2E8B57' },
  { id: 'SUGAR_CANE', category: 'blocks', color: '#2E8B57' },
  { id: 'CACTUS', category: 'blocks', color: '#2E8B57' },
  { id: 'VINE', category: 'blocks', color: '#2E8B57' },
  { id: 'LILY_PAD', category: 'blocks', color: '#2E8B57' },
  { id: 'SPORE_BLOSSOM', category: 'blocks', color: '#FF69B4' },
  { id: 'MOSS_BLOCK', category: 'blocks', color: '#2E8B57' },
  { id: 'MOSS_CARPET', category: 'blocks', color: '#2E8B57' },
  { id: 'HANGING_ROOTS', category: 'blocks', color: '#8B4513' },
  { id: 'BIG_DRIPLEAF', category: 'blocks', color: '#2E8B57' },
  { id: 'SMALL_DRIPLEAF', category: 'blocks', color: '#2E8B57' },
  { id: 'PINK_PETALS', category: 'blocks', color: '#FFB6C1' },
  { id: 'SPORE_BLOSSOM', category: 'blocks', color: '#FF69B4' },
  { id: 'SCULK', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_VEIN', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_CATALYST', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_SHRIEKER', category: 'blocks', color: '#00CED1' },
  { id: 'SCULK_SENSOR', category: 'blocks', color: '#00CED1' },
  { id: 'CALIBRATED_SCULK_SENSOR', category: 'blocks', color: '#00CED1' },
  { id: 'REINFORCED_DEEPSLATE', category: 'blocks', color: '#3A3A3A' },
  { id: 'END_PORTAL_FRAME', category: 'blocks', color: '#2E8B57' },
  { id: 'DRAGON_EGG', category: 'blocks', color: '#2E8B57' },
  { id: 'COMMAND_BLOCK', category: 'blocks', color: '#FFB6C1' },
  { id: 'REPEATING_COMMAND_BLOCK', category: 'blocks', color: '#4169E1' },
  { id: 'CHAIN_COMMAND_BLOCK', category: 'blocks', color: '#7CFC00' },
  { id: 'STRUCTURE_BLOCK', category: 'blocks', color: '#7CFC00' },
  { id: 'STRUCTURE_VOID', category: 'blocks', color: '#F5F5F5' },
  { id: 'JIGSAW', category: 'blocks', color: '#800080' },
  { id: 'BARRIER', category: 'blocks', color: '#FF0000' },
  { id: 'LIGHT', category: 'blocks', color: '#FFD700' },
  { id: 'TRIAL_SPAWNER', category: 'blocks', color: '#FFD700' },
  { id: 'OMINOUS_TRIAL_SPAWNER', category: 'blocks', color: '#00CED1' },
  { id: 'VAULT', category: 'blocks', color: '#B87333' },
  { id: 'OMINOUS_VAULT', category: 'blocks', color: '#00CED1' },
  { id: 'CREAKING_HEART', category: 'blocks', color: '#8B4513' },
  { id: 'PALE_OAK_PLANKS', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_LOG', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_WOOD', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_LEAVES', category: 'blocks', color: '#D3D3D3' },
  { id: 'PALE_MOSS_BLOCK', category: 'blocks', color: '#C0C0C0' },
  { id: 'PALE_MOSS_CARPET', category: 'blocks', color: '#C0C0C0' },
  { id: 'PALE_HANGING_MOSS', category: 'blocks', color: '#C0C0C0' },
  { id: 'OPEN_EYEBLOSSOM', category: 'blocks', color: '#C0C0C0' },
  { id: 'CLOSED_EYEBLOSSOM', category: 'blocks', color: '#808080' },
  { id: 'CREAKING_SPAWN_EGG', category: 'misc', color: '#C0C0C0' },
  { id: 'PALE_OAK_SAPLING', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_SIGN', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_HANGING_SIGN', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_DOOR', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_TRAPDOOR', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_PRESSURE_PLATE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_BUTTON', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_FENCE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_FENCE_GATE', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_STAIRS', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_SLAB', category: 'blocks', color: '#E3E3E3' },
  { id: 'PALE_OAK_BOAT', category: 'transport', color: '#E3E3E3' },
  { id: 'PALE_OAK_CHEST_BOAT', category: 'transport', color: '#E3E3E3' },
  { id: 'ACACIA_BOAT', category: 'transport', color: '#D2691E' },
  { id: 'ACACIA_CHEST_BOAT', category: 'transport', color: '#D2691E' },
  { id: 'BAMBOO_RAFT', category: 'transport', color: '#D2B48C' },
  { id: 'BAMBOO_CHEST_RAFT', category: 'transport', color: '#D2B48C' },
  { id: 'BIRCH_BOAT', category: 'transport', color: '#D2B48C' },
  { id: 'BIRCH_CHEST_BOAT', category: 'transport', color: '#D2B48C' },
  { id: 'CHERRY_BOAT', category: 'transport', color: '#FFB7C5' },
  { id: 'CHERRY_CHEST_BOAT', category: 'transport', color: '#FFB7C5' },
  { id: 'DARK_OAK_BOAT', category: 'transport', color: '#3E2723' },
  { id: 'DARK_OAK_CHEST_BOAT', category: 'transport', color: '#3E2723' },
  { id: 'JUNGLE_BOAT', category: 'transport', color: '#8B6914' },
  { id: 'JUNGLE_CHEST_BOAT', category: 'transport', color: '#8B6914' },
  { id: 'MANGROVE_BOAT', category: 'transport', color: '#8B4513' },
  { id: 'MANGROVE_CHEST_BOAT', category: 'transport', color: '#8B4513' },
  { id: 'OAK_CHEST_BOAT', category: 'transport', color: '#B3814F' },
  { id: 'SPRUCE_BOAT', category: 'transport', color: '#6F4E37' },
  { id: 'SPRUCE_CHEST_BOAT', category: 'transport', color: '#6F4E37' },
  { id: 'TNT', category: 'blocks', color: '#FF0000' },
  { id: 'BOOKSHELF', category: 'blocks', color: '#8B4513' },
  { id: 'MOSSY_COBBLESTONE', category: 'blocks', color: '#6E8B5E' },
];

appendDerivedEntries(ATLAS);

const ATLAS_MAP = new Map<string, AtlasEntry>();
for (const entry of ATLAS) {
  ATLAS_MAP.set(entry.id, entry);
}

function appendDerivedEntries(entries: AtlasEntry[]) {
  const baseColors: Record<string, string> = {
    WHITE: '#FFFFFF',
    ORANGE: '#FF8C00',
    MAGENTA: '#FF00FF',
    LIGHT_BLUE: '#ADD8E6',
    YELLOW: '#FFD700',
    LIME: '#32CD32',
    PINK: '#FFB6C1',
    GRAY: '#808080',
    LIGHT_GRAY: '#D3D3D3',
    CYAN: '#00FFFF',
    PURPLE: '#800080',
    BLUE: '#0000FF',
    BROWN: '#8B4513',
    GREEN: '#008000',
    RED: '#FF0000',
    BLACK: '#000000',
  };

  for (const [name, color] of Object.entries(baseColors)) {
    pushIfMissing(entries, { id: `${name}_STAINED_GLASS`, category: 'blocks', color });
    pushIfMissing(entries, { id: `${name}_STAINED_GLASS_PANE`, category: 'blocks', color });
  }

  pushIfMissing(entries, { id: 'SPECTRAL_ARROW', category: 'combat', color: '#FFFF55' });
  pushIfMissing(entries, { id: 'TIPPED_ARROW', category: 'combat', color: '#E3E3E3' });
  pushIfMissing(entries, { id: 'BLACK_STAINED_GLASS', category: 'blocks', color: '#000000' });
  pushIfMissing(entries, { id: 'BLACK_STAINED_GLASS_PANE', category: 'blocks', color: '#000000' });
  pushIfMissing(entries, { id: 'GLASS_PANE', category: 'blocks', color: '#D0E8F2' });
}

function pushIfMissing(entries: AtlasEntry[], entry: AtlasEntry) {
  if (!entries.some((candidate) => candidate.id === entry.id)) {
    entries.push(entry);
  }
}

export function getAtlasEntry(id: string): AtlasEntry | undefined {
  return ATLAS_MAP.get(id.toUpperCase());
}

export function getItemAtlasEntries(query?: string): AtlasEntry[] {
  const q = query?.toUpperCase() ?? '';
  return ATLAS.filter((e) => e.id.includes(q));
}

export function getFallbackColor(material: string): string {
  return getAtlasEntry(material)?.color ?? '#AAAAAA';
}
